
CREATE TABLE `#__eaiou_papers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `title` VARCHAR(255),
  `slug` VARCHAR(255),
  `abstract` MEDIUMTEXT,
  `doi` VARCHAR(191),
  `keywords` TEXT,
  `authors_json` MEDIUMTEXT,
  `authorship_mode` VARCHAR(16),
  `status` VARCHAR(32),
  `submission_version` VARCHAR(50),
  `submission_date` DATETIME,
  `acceptance_date` DATETIME,
  `publication_date` DATETIME,
  `bundle_path` VARCHAR(512),
  `thumbnail` VARCHAR(512),
  KEY `idx_papers_status` (`status`),
  KEY `idx_papers_pubdate` (`publication_date`),
  KEY `idx_papers_slug` (`slug`),
  KEY `idx_papers_doi` (`doi`)
);

CREATE TABLE `#__eaiou_versions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `paper_id` INT,
  `label` VARCHAR(50),
  `file_path` VARCHAR(512),
  `ai_flag` TINYINT,
  `ai_model_name` VARCHAR(128),
  `generated_at` DATETIME,
  `notes` TEXT,
  KEY `idx_versions_paper_label` (`paper_id`, `label`),
  KEY `idx_versions_model` (`ai_model_name`)
);

CREATE TABLE `#__eaiou_ai_sessions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `paper_id` INT,
  `session_label` VARCHAR(100),
  `ai_model_name` VARCHAR(128),
  `start_time` DATETIME,
  `end_time` DATETIME,
  `tokens_in` INT,
  `tokens_out` INT,
  `redaction_status` VARCHAR(16),
  `session_notes` MEDIUMTEXT,
  `session_hash` CHAR(64),
  KEY `idx_ai_sessions_paper` (`paper_id`),
  KEY `idx_ai_sessions_model` (`ai_model_name`),
  KEY `idx_ai_sessions_start` (`start_time`)
);

CREATE TABLE `#__eaiou_didntmakeit` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `session_id` INT,
  `prompt_text` MEDIUMTEXT,
  `response_text` MEDIUMTEXT,
  `redacted` TINYINT,
  `redaction_hash` CHAR(64),
  KEY `idx_didntmakeit_session` (`session_id`)
);

CREATE TABLE `#__eaiou_remsearch` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `paper_id` INT,
  `citation_title` VARCHAR(512),
  `citation_source` VARCHAR(255),
  `citation_link` VARCHAR(512),
  `source_type` VARCHAR(32),
  `used` TINYINT,
  `reason_unused` VARCHAR(32),
  KEY `idx_remsearch_paper_used` (`paper_id`, `used`)
);

CREATE TABLE `#__eaiou_review_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `paper_id` INT,
  `reviewer_user_id` INT,
  `review_date` DATETIME,
  `version_reviewed` VARCHAR(50),
  `rubric_overall` TINYINT,
  `rubric_originality` TINYINT,
  `rubric_methodology` TINYINT,
  `rubric_transparency` TINYINT,
  `rubric_ai_disclosure` TINYINT,
  `labels_json` MEDIUMTEXT,
  `review_notes` MEDIUMTEXT,
  KEY `idx_review_logs_paper_date` (`paper_id`, `review_date`),
  KEY `idx_review_logs_reviewer` (`reviewer_user_id`)
);

CREATE TABLE `#__eaiou_attribution_log` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `paper_id` INT,
  `contributor_name` VARCHAR(255),
  `role_description` VARCHAR(255),
  `contribution_type` VARCHAR(32),
  `ai_tool_used` VARCHAR(128),
  `timestamp` DATETIME,
  KEY `idx_attrlog_paper_type` (`paper_id`, `contribution_type`)
);

CREATE TABLE `#__eaiou_plugins_used` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `paper_id` INT,
  `plugin_name` VARCHAR(191),
  `plugin_type` VARCHAR(64),
  `execution_context` VARCHAR(128),
  `exec_log_path` VARCHAR(512),
  KEY `idx_plugins_used_paper_plugin` (`paper_id`, `plugin_name`)
);

CREATE TABLE `#__eaiou_api_keys` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `user_id` INT,
  `api_key_hash` CHAR(64),
  `description` VARCHAR(255),
  `access_level` VARCHAR(16),
  `status` VARCHAR(16),
  KEY `idx_api_keys_user_status` (`user_id`, `status`),
  KEY `idx_api_keys_hash` (`api_key_hash`)
);

CREATE TABLE `#__eaiou_api_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `state` TINYINT,
  `access` TINYINT,
  `ordering` INT,
  `created` DATETIME,
  `created_by` INT,
  `modified` DATETIME,
  `modified_by` INT,
  `checked_out` INT,
  `checked_out_time` DATETIME,
  `api_key_id` INT,
  `endpoint` VARCHAR(255),
  `request_data` MEDIUMTEXT,
  `response_code` SMALLINT,
  `timestamp` DATETIME,
  KEY `idx_api_logs_key_time` (`api_key_id`, `timestamp`)
);
