"""
eaiou Agent Team Orchestrator
Sequences: Author → Mira → Scorch QC → Seal

Usage:
    cd /scratch/repos/eaiou
    python -m agents.orchestrator

    # Custom topic:
    PAPER_TOPIC="your topic" python -m agents.orchestrator

    # Against local dev:
    EAIOU_BASE_URL=http://localhost:8000 python -m agents.orchestrator

    # Capture Scorch output:
    python -m agents.orchestrator 2>scorch_log.txt
"""
import sys
from agents import config
from agents.eaiou_client import EaiouClient
from agents.scorch import Scorch
from agents.author_agent import AuthorAgent
from agents.mira import MiraAgent


def run() -> int:
    """Run the full agent lifecycle. Returns exit code (0=success, 1=failure)."""
    scorch = Scorch(verbose=True)
    client = EaiouClient()
    author = AuthorAgent(client, scorch)
    mira = MiraAgent(client, scorch)
    paper_id: int | None = None

    try:
        # ── 1. Login ──────────────────────────────────────────────────────────
        with scorch.step("auth_login"):
            client.login()

        # ── 2. Generate paper metadata ────────────────────────────────────────
        with scorch.step("generate_metadata"):
            title, abstract, keywords = author.generate_paper_metadata()

        # ── 3. Pre-flight checks (Scorch) ─────────────────────────────────────
        word_count = len(abstract.split())
        if word_count < 80:
            scorch.warn(f"Abstract {word_count} words — regenerating to ≥85", step="preflight")
            abstract = author.regenerate_abstract(title, min_words=85)

        # ── 4. Submit paper ───────────────────────────────────────────────────
        with scorch.step("submit_paper"):
            paper_id = client.submit_paper(
                title=title,
                abstract=abstract,
                author_name=config.AUTHOR_NAME,
                orcid=config.AUTHOR_ORCID,
                keywords=keywords,
                ai_disclosure_level="collaborative",
                ai_disclosure_notes="Paper content generated by Claude claude-sonnet-4-6 under human oversight.",
            )
            scorch.info(f"Paper created: id={paper_id}", step="submit_paper")

        # ── 5. Generate section structure ─────────────────────────────────────
        with scorch.step("generate_structure"):
            structure = client.generate_structure(title, abstract, keywords=keywords)
            sections_plan = structure.get("sections", [])

        # ── 6. Ensure References section exists ───────────────────────────────
        scorch.observe_preflight(abstract, sections_plan)
        has_ref = any(
            "ref" in s.get("name", "").lower() or "bibliograph" in s.get("name", "").lower()
            for s in sections_plan
        )
        if not has_ref:
            sections_plan.append({"name": "References", "focus": "Bibliography and citations"})

        # ── 7. Create sections in DB and populate with content ────────────────
        section_ids: dict[str, int] = {}
        for i, sec in enumerate(sections_plan):
            with scorch.step(f"create_section_{i}_{sec['name'][:20]}"):
                content = author.generate_section_content(
                    sec["name"], sec.get("focus", ""), abstract
                )
                result = client.create_section(
                    paper_id=paper_id,
                    section_name=sec["name"],
                    section_order=i,
                    section_notes=content,
                )
                section_ids[sec["name"]] = result["section_id"]

        # ── 8. Interrogate (satisfies INTERROGATION gate) ─────────────────────
        with scorch.step("interrogate"):
            question = author.generate_interrogation_question(title, abstract)
            interrog_result = client.interrogate(paper_id, question)
            interrog_response = interrog_result["response"]
            scorch.info(
                f"Expert: {interrog_result.get('expert_domain', '?')} — {interrog_result.get('expert_title', '?')}",
                step="interrogate",
            )

        # ── 9. Seed first section from interrogation response ─────────────────
        with scorch.step("seed_section"):
            first_name = sections_plan[0]["name"]
            first_id = section_ids[first_name]
            client.seed_section(paper_id, first_id, interrog_response, seeded_from="interrogation")

        # ── 10. Load Mira as Defender module ──────────────────────────────────
        mira.load(paper_id)

        # ── 11. Mira reads the document (activates module) ────────────────────
        mira.read(paper_id)

        # ── 12. Mira red-teams (satisfies RED_TEAM_RAN gate) ──────────────────
        mira.redteam(paper_id, focus=f"Methodology and claims in: {title}")

        # ── 13. Mid-point gate check ──────────────────────────────────────────
        with scorch.step("gate_check_mid"):
            gates_mid = client.check_gates(paper_id)
            scorch.observe_gate(gates_mid, label="mid")

        # ── 14. Run volley audit (satisfies VOLLEY_RAN gate) ──────────────────
        with scorch.step("volley_audit"):
            audit_result = client.run_audit(paper_id)
            round_number = audit_result["round"]
            scorch.observe_audit(audit_result, round_number)

        # ── 15. Respond to audit (satisfies VOLLEY_RESOLVED gate) ─────────────
        with scorch.step("volley_respond"):
            audit_response = author.generate_audit_response(audit_result)
            client.respond_to_audit(paper_id, round_number, audit_response)

        # ── 16. Final gate check ──────────────────────────────────────────────
        with scorch.step("gate_check_final"):
            gates_final = client.check_gates(paper_id)
            scorch.observe_gate(gates_final, label="final")

        # ── 17. Remediate any failing gates ───────────────────────────────────
        if not gates_final.get("all_passed"):
            failed = [c for c in gates_final["checks"] if not c["passed"]]
            scorch.warn(
                f"{len(failed)} gate(s) still failing — attempting remediation",
                step="remediate",
                data={"failed": [c["code"] for c in failed]},
            )
            author.remediate_gates(failed, paper_id, section_ids, client)
            # Re-check after remediation
            with scorch.step("gate_check_post_remediate"):
                gates_final = client.check_gates(paper_id)
                scorch.observe_gate(gates_final, label="post_remediate")

        # ── 18. Seal ──────────────────────────────────────────────────────────
        if not gates_final.get("all_passed"):
            scorch.warn("Seal blocked — gates still failing after remediation", step="seal")
            scorch.print_report(paper_id)
            return 1

        with scorch.step("seal_paper"):
            seal_result = client.seal_paper(paper_id)
            scorch.observe_seal(seal_result)

        # ── 19. Report ────────────────────────────────────────────────────────
        scorch.print_report(paper_id)
        print(f"\n=== RUN COMPLETE ===")
        print(f"paper_id:     {paper_id}")
        print(f"sealed:       {seal_result.get('sealed')}")
        print(f"audit_status: {seal_result.get('audit_status')}")
        print(f"q_signal:     {seal_result.get('q_signal')}")
        print(f"q_label:      {seal_result.get('q_label')}")
        return 0 if seal_result.get("sealed") else 1

    except Exception as exc:
        scorch.warn(f"Unhandled exception: {exc}", step="orchestrator")
        scorch.print_report(paper_id)
        raise


def main():
    sys.exit(run())


if __name__ == "__main__":
    main()
